### ISSUE TITLE
Using ${name} in IDs and also as hostname breaks with hyphens or underscores

### ISSUE THREAD

**Issue by werdnum** [bogorad/m5stack-m5NanoC6-esphome#1]
I'm trying something like this:

```
substitutions:
  name: office_bluetooth_proxy
  friendly_name: Office Bluetooth Proxy
  
packages:
  nanoc6: github://bogorad/m5stack-m5NanoC6-esphome/packages/generic_m5stack-nano-c6.yaml
```

If I have hyphens in the name:

```
Failed config

button.safe_mode: [source .esphome/packages/fcae6f5c/packages/button.yaml:2]
  platform: safe_mode
  name: Safe Mode Boot
  entity_category: diagnostic

  Dashes are not supported in IDs, please use underscores instead.
  id: office-bluetooth-proxy_safe_mode_boot
```

If I use underscores:

```
WARNING 'office_bluetooth_proxy': Using the '_' (underscore) character in the hostname is discouraged as it can cause problems with some DHCP and local name services. For more information, see https://esphome.io/guides/faq.html#why-shouldn-t-i-use-underscores-in-my-device-name
```

Should somehow translate hyphens to underscores when using ${name} in an ID, OR have separate options for the id prefix and hostname, OR just drop using the name in the IDs anyway because Home Assistant kinda prefers it that way anyway (see e.g. https://github.com/home-assistant/core/issues/97483)
